compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
    - glibc
  os:
    - current
    - linux
    - macos

yarnPath: .yarn/releases/yarn-4.9.1.cjs
