// Canonical structured resume. Seeded from the PDF at
// app/public/James Andrew Smith - Resume.pdf and read by the site graph
// (app/libs/agent/site-graph.server.ts), which feeds /agent/resume.json,
// /resume.md and the Person structured data.
//
// The PDF is not read, linked or generated by the machine layer: this file is
// the only source for it, so a change to the PDF must be mirrored here by
// hand. Public fields only - never add email, phone, or address, and keep
// every location to the city. Add a company `url` only if the site's own
// content already links to it.

import type { TopicSlug } from "./topics"

type ResumeCompany = {
  // Stable join key shared with recommendations and post front matter.
  slug: string
  name: string
  url?: string
}

type ResumeSkillGroup = {
  group: string
  items: string[]
}

type ResumeExperience = {
  company: ResumeCompany
  title: string
  // YYYY-MM
  start: string
  // YYYY-MM, or "present"
  end: string
  // City level only.
  location?: string
  summary: string
  technologies: string[]
  highlights: string[]
}

type ResumeAdditionalRole = {
  company: string
  title: string
}

type ResumeEducation = {
  school: string
  degree: string
  field: string
}

type ResumeCommunityItem = {
  label: string
  url?: string
}

type Resume = {
  summary: string
  skills: ResumeSkillGroup[]
  experience: ResumeExperience[]
  additional: ResumeAdditionalRole[]
  education: ResumeEducation[]
  talksAndOss: ResumeCommunityItem[]
}

const resume = {
  summary:
    "Staff-level software engineer with expansive experience designing scalable, high-impact front-end systems at enterprise scale. Proven leader in front-end architecture, developer experience, and testing strategy using React.js, TypeScript, and GraphQL. Trusted mentor across teams for building sustainable engineering practices. Enjoy mentoring and contributing to open source, including contributions to Gatsby and Cypress. Uses system languages C# and Node.js to build scalable, distributed systems deployed with Kubernetes, Docker, and cloud native solutions.",

  skills: [
    {
      group: "Languages & Frameworks",
      items: ["TypeScript", "React.js", "Node.js", "Next.js", "C#", "JavaScript", "GraphQL", "Redux", "Webpack", "esbuild", "Vite", "Remix"],
    },
    {
      group: "Architecture & Design",
      items: ["Distributed Systems", "Front-end Architecture", "Microservices", "Monorepo (Nx, Yarn PnP)", "Component Libraries", "Cloud Architecture", "Kubernetes", "Docker", "SQL", "NoSQL Databases"],
    },
    {
      group: "Testing & Quality",
      items: ["Jest", "Mocha", "Cypress", "End-to-End", "Component", "Visual Regression", "NUnit", "xUnit", "MSTest", "Ephemeral Environments"],
    },
    {
      group: "Practices & Agility",
      items: ["TDD (Test-Driven Development)", "XP (Pair Programming)", "Kanban", "Monte-Carlo"],
    },
  ],

  experience: [
    {
      company: { slug: "microsoft", name: "Microsoft" },
      title: "Staff-level Software Engineer",
      start: "2020-12",
      end: "present",
      location: "Atlanta, GA",
      summary:
        "Develop distributed CMS, focusing on authoring tooling and content delivery, for support.microsoft.com, Office applications, and Windows. Influential technical leadership and mentorship across 5 teams.",
      technologies: ["TypeScript", "React.js", "Node.js", "Next.js", "Redux", "GraphQL", "C#", "microservices", "Nx", "Azure", "TDD", "XP", "git", "Kanban", "ADR"],
      highlights: [
        "Architected and implemented front-end platform, across 3 teams, powering CMS systems for support.microsoft.com, Office, and Windows, serving 2B+ users and handling 1B+ requests monthly.",
        "Designed and led CQRS systems implementation across 3 teams, increasing key performance metrics by over 95% and customer satisfaction by 50%.",
        "Designed and implemented scalable authoring tool to enable content onboarding for Co-pilot Labs and partner teams, accelerating Microsoft's generative AI initiative.",
        "Led strategic adoption of Jest and Cypress across 8 teams, increasing test coverage from 0% to 60% and reducing support costs by 50%.",
        "Consolidated microservices into a monorepo with Nx and Yarn PnP, improving CI cycle time by 95% and enhancing developer workflows.",
        "Created an open-source AI-driven project forecasting tool, improving timeline communication to leadership by 80%.",
        "Ensured alignment of 5 teams of 30+ engineers on engineering north star with the use of ADRs (Architectural Design Records) and an architectural review committee.",
      ],
    },
    {
      company: { slug: "experience", name: "Experience" },
      title: "Lead Front-End Engineer (Staff-level)",
      start: "2019-06",
      end: "2020-12",
      location: "Atlanta, GA",
      summary: "Owned front-end architecture across 2 cross-functional teams. Partnered with leadership to deliver scalable user-facing platforms in the live event and ticketing space.",
      technologies: ["TypeScript", "React.js", "Node.js", "Redux", "Java", "Groovy", "Jest", "Cypress", "Docker", "microservices", "AWS", "git", "TDD", "Scrum"],
      highlights: [
        "Championed Cypress-based testing pipelines integrated with Docker-based ephemeral CI environments.",
        "Collaborated with product, design and engineering teams to implement a design language and accompanying React.js component library.",
        "Introduced processes and testing practices, such as \"Three Amigos,\" improving engineering teams' delivery speed.",
      ],
    },
    {
      company: { slug: "versionone-collabnet", name: "VersionOne CollabNet" },
      title: "Senior Software Engineer",
      start: "2014-09",
      end: "2019-06",
      location: "Atlanta, GA",
      summary: "Technical lead for high-profile features on flagship Agile Lifecycle Management product in an XP and TDD environment.",
      technologies: ["JavaScript", "React.js", "Redux", "AngularJs", "Backbone.JS", "jQuery", "C#", "MVC.NET", "NUnit", "Node.js", "TDD", "XP", "gulp", "git", "Kanban"],
      highlights: [
        "Led modernization of proprietary JavaScript front-end to ES6 and React.js across 5 teams, reducing tech debt by 30%.",
        "Built and maintained an OSS React component library and JavaScript SDK used internally and by Fortune 500 customers.",
        "Served as technical leader and subject matter expert for front-end architecture and tooling strategy across 2 products and 5 teams.",
        "Delivered 3 high-profile projects critical to product's market strategy: product road mapping, time sheets, and a complex filtering experience.",
      ],
    },
    {
      company: { slug: "matrix-professional-services", name: "Matrix Professional Services" },
      title: "Senior Software Engineer",
      start: "2013-02",
      end: "2014-09",
      location: "Atlanta, GA",
      summary: "Focused on full-stack development using C#, JavaScript, and TDD for 3 major clients.",
      technologies: ["C#", "MVC.NET", "Node.js", "JavaScript", "React.js", "jQuery", "KnockoutJS", "TDD", "Jasmine", "Karma", "MSTest", "Scrum", "grunt", "git"],
      highlights: [
        "Crafted over 4 unique developer workshops on test-driven development and front-end best practices presented to groups of 7+ engineers.",
        "Implemented CI-ready test frameworks (Jasmine, Mocha, Karma) integrated with Gulp/Grunt, reducing defects by ~60%.",
        "Created a redesigned e-commerce checkout for a major client, reducing steps by 50% and improving conversion rates.",
      ],
    },
  ],

  additional: [
    { company: "MModal", title: "Software Engineer" },
    { company: "Response Mine Interactive", title: "Senior Software Engineer" },
    { company: "Daxko", title: "Senior Software Engineer" },
    { company: "MedSeek", title: "Software Engineer 3" },
    { company: "Intermark Interactive", title: "Software Engineer 3" },
    { company: "Columbus Technical College", title: "Adjunct Faculty" },
  ],

  education: [{ school: "Columbus State University", degree: "Bachelor of Science (BS)", field: "Computer Science" }],

  talksAndOss: [
    { label: "Mentor and open source contributor, including contributions to Gatsby and Cypress" },
    { label: "Co-founder of ReactATL Meetup, a community of over 4K members" },
    { label: "Delivered 7 workshops and presentations at major conferences, focused on React.js, Redux, and GraphQL" },
  ],
} satisfies Resume

// Resume skills that the site's own posts can back up, keyed by the exact
// skill name above. Drives the expertise evidence map: a skill is "backed" by
// every post tagged with its topic.
const skillTopics: Record<string, TopicSlug> = {
  "React.js": "react",
  "Node.js": "nodejs",
  JavaScript: "javascript",
  GraphQL: "graphql",
  Kubernetes: "kubernetes",
  Jest: "jest",
  Mocha: "mocha",
  "TDD (Test-Driven Development)": "tdd",
  "Monte-Carlo": "forecasting",
}

export { resume, skillTopics }
export type { Resume, ResumeAdditionalRole, ResumeCommunityItem, ResumeCompany, ResumeEducation, ResumeExperience, ResumeSkillGroup }
