import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/_index.tsx"),
  route("posts", "routes/posts.tsx", [route(":id", "routes/posts.$id.tsx")]),
  route("recommendations", "routes/recommendations.tsx"),
  route("agent/recommendations.json", "routes/agent.recommendations.json.ts"),
  route("tags/:id", "routes/tags.$id.tsx"),
  route("connect", "routes/connect.tsx"),
  route("connect-with-me", "routes/connect-with-me.tsx"),
  route("robots.txt", "routes/robots.txt.ts"),
  route("sitemap.xml", "routes/sitemap.xml.ts"),
  route("feed.xml", "routes/feed.xml.ts"),
  route("agent/resume.json", "routes/agent.resume-json.ts"),
  route("resume.md", "routes/resume-md.ts"),
  route("agent/posts.json", "routes/agent.posts-json.ts"),
  route("agent/projects.json", "routes/agent.projects-json.ts"),
  route("index.md", "routes/index-md.ts"),
  route("posts.md", "routes/posts-index-md.ts"),
  route("posts/:id.md", "routes/posts-md.ts"),
  route("tags/:id.md", "routes/tags-md.ts"),
  route("recommendations.md", "routes/recommendations-md.ts"),
  route("llms.txt", "routes/llms-txt.ts"),
  route("llms-full.txt", "routes/llms-full-txt.ts"),
] satisfies RouteConfig
