name: Deploy PR ephemeral environment
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: andrew-codes/andrew.codes
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andrew-codes/gh-action-runner:latest
    steps:
      - name: ⬇️ Checkout source code
        uses: actions/checkout@v3

      - name: 🚀 Deploy emphemeral environment for pull request
        uses: superfly/flyctl-actions@1.4
        with:
          version: "0.1.25"
          args: "deploy --config fly.staging.toml --remote-only --build-arg PR_NUMBER=${{ env.PR_NUMBER }} --build-arg DEPLOYMENT_ENV=staging"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
