name: Deploy PR ephemeral environment
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: andrew-codes/andrew.codes
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' && github.event.pull_request.head.repo.full_name != 'your/full_repo_name' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andrew-codes/gh-action-runner:latest
    steps:
      - name: ⬇️ Checkout source code
        uses: actions/checkout@v3

      - name: 🚀 Deploy emphemeral environment for pull request
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy --config fly.staging.toml --remote-only -e PR_NUMBER=${{ env.PR_NUMBER }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
